# Import Libraries

In [1]:
# load packages
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Data Collection & Analysis

In [2]:
# load dataset
bank_data = pd.read_csv('/Users/macbookpro/Desktop/End-to-End Projects/bank_customer/data/BankCustomerData.csv')
bank_data

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,term_deposit
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42634,21,student,single,secondary,no,2488,no,no,telephone,12,jan,661,2,92,1,success,yes
42635,87,retired,married,primary,no,2190,no,no,telephone,12,jan,512,2,-1,0,unknown,yes
42636,34,blue-collar,married,primary,no,6718,no,no,cellular,13,jan,278,4,97,1,other,no
42637,22,student,single,secondary,no,254,no,no,cellular,13,jan,143,2,-1,0,unknown,yes
42638,32,management,single,tertiary,no,1962,no,no,cellular,13,jan,130,1,-1,0,unknown,no

In [3]:
# first 5 rows
bank_data.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,term_deposit
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [4]:
# last 5 rows
bank_data.tail()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,term_deposit
42634,21,student,single,secondary,no,2488,no,no,telephone,12,jan,661,2,92,1,success,yes
42635,87,retired,married,primary,no,2190,no,no,telephone,12,jan,512,2,-1,0,unknown,yes
42636,34,blue-collar,married,primary,no,6718,no,no,cellular,13,jan,278,4,97,1,other,no
42637,22,student,single,secondary,no,254,no,no,cellular,13,jan,143,2,-1,0,unknown,yes
42638,32,management,single,tertiary,no,1962,no,no,cellular,13,jan,130,1,-1,0,unknown,no

In [5]:
# dataset info
bank_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42639 entries, 0 to 42638
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           42639 non-null  int64
 1   job           42639 non-null  object
 2   marital       42639 non-null  object
 3   education     42639 non-null  object
 4   default       42639 non-null  object
 5   balance       42639 non-null  int64
 6   housing       42639 non-null  object
 7   loan          42639 non-null  object
 8   contact       42639 non-null  object
 9   day           42639 non-null  int64
 10  month         42639 non-null  object
 11  duration      42639 non-null  int64
 12  campaign      42639 non-null  int64
 13  pdays         42639 non-null  int64
 14  previous      42639 non-null  int64
 15  poutcome      42639 non-null  object
 16  term_deposit  42639 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.5+ MB

In [6]:
# check for missing values
bank_data.isnull().sum()

age             0
job             0
marital         0
education       0
default         0
balance         0
housing         0
loan            0
contact         0
day             0
month           0
duration        0
campaign        0
pdays           0
previous        0
poutcome        0
term_deposit    0
dtype: int64

In [7]:
# drop the target column
X = bank_data.drop('term_deposit', axis=1)
Y = bank_data['term_deposit']

In [8]:
print(X)

       age           job  marital  education default  balance housing loan  \
0       58    management  married   tertiary      no     2143     yes   no
1       44    technician   single  secondary      no       29     yes   no
2       33  entrepreneur  married  secondary      no        2     yes  yes
3       47   blue-collar  married    unknown      no     1506     yes   no
4       33       unknown   single    unknown      no        1      no   no
...    ...           ...      ...        ...     ...      ...     ...  ...
42634   21       student   single  secondary      no     2488      no   no
42635   87       retired  married    primary      no     2190      no   no
42636   34   blue-collar  married    primary      no     6718      no   no
42637   22       student   single  secondary      no      254      no   no
42638   32    management   single   tertiary      no     1962      no   no

         contact  day month  duration  campaign  pdays  previous poutcome
0        unknown    5   may       261         1     -1         0  unknown
1        unknown    5   may       151         1     -1         0  unknown
2        unknown    5   may        76         1     -1         0  unknown
3        unknown    5   may        92         1     -1         0  unknown
4        unknown    5   may       198         1     -1         0  unknown
...          ...  ...   ...       ...       ...    ...       ...      ...
42634  telephone   12   jan       661         2     92         1  success
42635  telephone   12   jan       512         2     -1         0  unknown
42636   cellular   13   jan       278         4     97         1    other
42637   cellular   13   jan       143         2     -1         0  unknown
42638   cellular   13   jan       130         1     -1         0  unknown

[42639 rows x 16 columns]

In [9]:
print(Y)

0         no
1         no
2         no
3         no
4         no
        ...
42634    yes
42635    yes
42636     no
42637    yes
42638     no
Name: term_deposit, Length: 42639, dtype: object

In [10]:
print(X.columns)
print(len(X.columns))

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome'],
      dtype='object')
16